version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./public:/app/public
    working_dir: /app
