version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ./public:/app/public
    working_dir: /app

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/db
